spring:
  application:
    name: myconfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jamescaoBJ/systemParameterConfig.git
          search-paths: config-repo
          username: caoyange0412@163.com
          password: 1qaz2wsx!@#$%6789
server:
  port: 9091          
debug: false
